services:
  server:
    container_name: nextjs-server
    image: registry.digitalocean.com/ib-registry/ib2-frontend:paas-service-test_83c99bd63b2c881f8274a4c7382b89dc6e95dc83
    pull_policy: always
    environment:
      NODE_ENV: production
    networks:
      - dokploy-network
    ports:
      - 3000:3000
    env_file:
      - .env

  postgres:
    container_name: nextjs-postgres
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dokploy-network
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  db_data:

networks:
  dokploy-network:
    external: true