services:
  server:
    container_name: nextjs-server
    build:
      context: .
      dockerfile: deployment/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - docker.env
    networks:
      - nextjs

  postgres:
    image: postgres:16
    container_name: nextjs-postgres
    restart: always
    networks:
      - nextjs
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  db_data:

networks:
  nextjs:
    external: true